channels:
  # only used for README generation, see recipe/conda_build_config.yaml
  targets:
  - [ryanvolz, main]
github:
  user_or_org: ryanvolz
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pXAERvsxp6bcxfKUksZy4SgOJtRDqj8xWC9ZN4wb9vnwYJqJ3Iy3VCnaHbNtAT5sgEcTngpfy0HXjPxQ6ROm4s6R8Dftwv/dacH4rk1LPIRznYtJzT6P+jqW/S6+c3VBMJKAUIP7bkUefheRlH88jb0em+0UVtYA8nlQSX/W3Vchd1j5QPGu0Mn6JnzJfI4CVN/n9zjBlOjJUzUHArezMcklkkoBqHRVCyQLVgIP/mtNzrdq9Xo5UnjO/Tm8ak6F64PqsGkroPB/0BbAUPV7J0mJGcqJgNWqL5B8aXv1/uEb1leUaQFgwImbBA78rq1KAk/COWXKgXV8Qf3+54GuGtG1RdKlDujqTJa3KHteenXxlc+CPgH/2ENHKBa0awmlSwVi5kNbqvtzMwyWl7Hkf6nmOe5dHjHu6coVKbf/CqokfjgclXY3M+eBiYuHzAQfBLXnLu0L+cEaD2HtoaCI5TGYDtOidPHv/MG/nSmwEmbbTT6fTZ9XyMz728/Kwv3Ln9rgqZPEhjmuMv9ZqShDBNKpeG2HBAeHmcpjOolaT1N+eUs8ZvnjYWHHHhqezoXpuDoDRFJTR4hxfoUrBFegZvaUtd/xdH7cE695auDTiQxPPGy2Ii+BGTfWiia+9ae2s7q5pTPez4HlRnfS9w0H1tvGfdPkQDw0ySs0/dd67cg=
appveyor:
  secure:
    BINSTAR_TOKEN: VdjdJuU4p0EJN2odZG5M+ig8GWMsDzxqsWLd9fhZ2IPrMPz6a4YvBRcQrbVaSDYo
azure:
  user_or_org: rvolz
